-- MySQL Script generated by MySQL Workbench
-- Tue Jun 13 16:11:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb3 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`GUIDETURISTICHE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`GUIDETURISTICHE` (
  `Cognome` VARCHAR(40) NOT NULL,
  `Nome` VARCHAR(30) NOT NULL,
  `Eta` INT NULL DEFAULT NULL,
  `Sesso` VARCHAR(45) NULL DEFAULT NULL,
  `Lingue` VARCHAR(45) NULL DEFAULT NULL,
  `AnnoAbilitazione` INT NOT NULL,
  PRIMARY KEY (`Cognome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`OFFERTESPECIALI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OFFERTESPECIALI` (
  `IdOfferta` INT NOT NULL,
  `PercentualeSconto` DOUBLE NOT NULL,
  `Inizio` DATE NOT NULL CHECK (Data LIKE 'DD/MM/YYYY'),
  `Fine` DATE NOT NULL CHECK (Data LIKE 'DD/MM/YYYY'),
  PRIMARY KEY (`IdOfferta`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3
COMMENT = '		';


-- -----------------------------------------------------
-- Table `mydb`.`SOCIETA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SOCIETA` (
  `Nome` VARCHAR(60) NOT NULL,
  `Indirizzo` VARCHAR(60) NULL DEFAULT NULL,
  `Telefono` INT NULL DEFAULT NULL,
  `Email` VARCHAR(319) NULL DEFAULT NULL,
  PRIMARY KEY (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`VISITEGUIDATE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VISITEGUIDATE` (
  `IdVisita` INT NOT NULL CHECK (IdVisita > 0),
  `Nome` VARCHAR(25) NOT NULL,
  `Descrizione` VERCHAR(200) NOT NULL,
  `Citta` VARCHAR(20) NOT NULL,
  `MaxPartecipanti` INT NOT NULL CHECK (MaxPartecipanti > 0),
  `PrezzoBase` DOUBLE NOT NULL CHECK (PrezzoBase > 0),
  `Societa_Nome` VARCHAR(60) NULL,
  `Offerta` INT NULL DEFAULT NULL,
  `GuideTuristiche_Cognome` VARCHAR(40) NULL,
  PRIMARY KEY (`IdVisita`),
  INDEX `fk_VISITEGUIDATE_SOCIETA1_idx` (`Societa_Nome` ASC) VISIBLE,
  INDEX `fk_VISITEGUIDATE_OFFERTESPECIALI1_idx` (`Offerta` ASC) VISIBLE,
  INDEX `fk_VISITEGUIDATE_GUIDETURISTICHE1_idx` (`GuideTuristiche_Cognome` ASC) VISIBLE,
  CONSTRAINT `fk_VISITEGUIDATE_GUIDETURISTICHE1`
    FOREIGN KEY (`GuideTuristiche_Cognome`)
    REFERENCES `mydb`.`GUIDETURISTICHE` (`Cognome`),
  CONSTRAINT `fk_VISITEGUIDATE_OFFERTESPECIALI1`
    FOREIGN KEY (`Offerta`)
    REFERENCES `mydb`.`OFFERTESPECIALI` (`IdOfferta`),
  CONSTRAINT `fk_VISITEGUIDATE_SOCIETA1`
    FOREIGN KEY (`Societa_Nome`)
    REFERENCES `mydb`.`SOCIETA` (`Nome`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`OPZIONI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`OPZIONI` (
  `IdOpzione` INT NOT NULL CHECK (IdOpzione > 0),
  `Descrizione` BLOB NULL DEFAULT NULL,
  `Durata` INT NULL DEFAULT NULL,
  `Mezzo` VARCHAR(45) NULL DEFAULT NULL,
  `MaggiorazionePrezzo` DOUBLE NULL DEFAULT NULL,
  `VisiteGuida_IdVisita` INT NOT NULL,
  PRIMARY KEY (`IdOpzione`),
  INDEX `fk_OPZIONI_VISITEGUIDATE1_idx` (`VisiteGuida_IdVisita` ASC) VISIBLE,
  CONSTRAINT `fk_OPZIONI_VISITEGUIDATE1`
    FOREIGN KEY (`VisiteGuida_IdVisita`)
    REFERENCES `mydb`.`VISITEGUIDATE` (`IdVisita`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`UTENTIREGISTRATI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`UTENTIREGISTRATI` (
  `Email` VARCHAR(319) NOT NULL CHECK (Email LIKE '%@%') COMMENT 'Questo è come lo vedete, la mail ho messo massimo 319 caratteri perchè quello è lo standard\\\\\\\\nForse dovremmo mettere come Foreign Key (USERNAME) \\\\\\\\nDEVO AGGIUNGERE LA CONSTRAINT CHECK PASSWORD non so come si fa direttamente da mySQL',
  `Username` VARCHAR(20) NOT NULL,
  `Nome` VARCHAR(30) NOT NULL,
  `Cognome` VARCHAR(40) NOT NULL,
  `Password` VARCHAR(20) NOT NULL CHECK (LEN(Password) >= 8),
  PRIMARY KEY (`Email`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `mydb`.`PRENOTAZIONI`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRENOTAZIONI` (
  `Data` DATE NOT NULL CHECK (Data LIKE 'DD/MM/YYYY'),
  `Ora` TIME NOT NULL CHECK (Ora LIKE 'HH:MI'),
  `PrezzoTotale` INT NOT NULL,
  `Visita` INT NOT NULL,
  `EmailUtente` VARCHAR(20) NOT NULL,
  `Opzioni_IdOpzione` INT NOT NULL,
  PRIMARY KEY (`Visita`, `EmailUtente`),
  INDEX `fk_PRENOTAZIONI_UTENTIREGISTRATI_idx` (`EmailUtente` ASC) VISIBLE,
  INDEX `fk_PRENOTAZIONI_VISITEGUIDATE1_idx` (`Visita` ASC) VISIBLE,
  INDEX `fk_PRENOTAZIONI_OPZIONI1_idx` (`Opzioni_IdOpzione` ASC) VISIBLE,
  CONSTRAINT `fk_PRENOTAZIONI_OPZIONI1`
    FOREIGN KEY (`Opzioni_IdOpzione`)
    REFERENCES `mydb`.`OPZIONI` (`IdOpzione`),
  CONSTRAINT `fk_PRENOTAZIONI_UTENTIREGISTRATI`
    FOREIGN KEY (`EmailUtente`)
    REFERENCES `mydb`.`UTENTIREGISTRATI` (`Email`),
  CONSTRAINT `fk_PRENOTAZIONI_VISITEGUIDATE1`
    FOREIGN KEY (`Visita`)
    REFERENCES `mydb`.`VISITEGUIDATE` (`IdVisita`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
